name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  lint-and-test:
    name: Run lint checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        run: |
          poetry install
      - name: flake8
        run: poetry run flake8
      - name: mypy
        run: poetry run mypy .

