name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

env:
  POETRY_NO_INTERACTION: "1"
  POETRY_VERSION: "1.2.0"


jobs:
  lint-and-test:
    name: Run lint checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install poetry
        run: curl -sSL https://install.python-poetry.org | python3 - && chmod a+x /opt/poetry/bin/poetry
      - name: install
        run: poetry install
      - name: flake8
        run: poetry run flake8
      - name: mypy
        run: poetry run mypy .

